### ISSUE TITLE
Collaborate Connecting Watson Conversation to RTC Jazz

### ISSUE THREAD

**Issue by jobri720** [jazz-community/rtc-statushistory-presentation#11]
Apologizes for reaching out this way but I am working on a project where I would like to connect Watson Conversation API in RTC to be able to ask natural language questions about tasks and user stories in RTC. I'm not that familiar with RTC but understand Watson Conversation very well. Would you be interested in investigating this hypothesis with me? 

https://www.ibm.com/watson/developercloud/conversation/api/v1/#introduction

**Comment by innerjoin** [comment]
Hi @jobri720 
Thank you for reaching out to us and please excuse my late reply. To me, this sounds like a really interesting, but quite ambitious project you are working on. I would love to work on such kind of a project, but I don't want to raise false hopes as I'm quite busy in the next few months, so my engagement would be fairly limited. 

Would you mind to tell as a little more about the (business) goals you have for this project / what you want to achieve? Are you willing to open source your results? If you prefer, you can also get in touch with me through LinkedIn: www.linkedin[dot]com/in/[my-firstname]-[my-lastname]/
