### ISSUE TITLE
Does not work for servers with negative timezone offset

### ISSUE THREAD

**Issue by rjc570** [jazz-community/rtc-statushistory-presentation#12]
Should it work immediately after installation?  Do data ware house jobs need to run to pull the data?  I am not seeing any errors in the ccm.log file or in the browser developer window.  I just get a blank box.
![screen shot 2018-01-31 at 3 07 31 pm](https://user-images.githubusercontent.com/21124929/35645035-a18137cc-0698-11e8-9718-4cf5d4b2fe41.png)
![screen shot 2018-01-31 at 3 07 59 pm](https://user-images.githubusercontent.com/21124929/35645040-a7631fd4-0698-11e8-8c0a-f2db6d4e4544.png)
![screen shot 2018-01-31 at 3 10 46 pm](https://user-images.githubusercontent.com/21124929/35645147-ff01341a-0698-11e8-9265-8415f115d618.png)
 
![screen shot 2018-01-31 at 3 13 56 pm](https://user-images.githubusercontent.com/21124929/35645342-7daf50e4-0699-11e8-8295-7e980aaf2e7c.png)

**Comment by schneigu** [comment]
It should work immidiatly. DW is not involved. Data are from live DB.

**Comment by rjc570** [comment]
Is there some debugging technique I can use to troubleshoot?

**Comment by rjc570** [comment]
Should it say "Not Available" in the editor presentation when I am adding it?
![screen shot 2018-02-02 at 9 45 06 am](https://user-images.githubusercontent.com/21124929/35738774-d66d0ce8-07fd-11e8-88fc-02d4a4c5fb85.png)

I have also checked the deployment logs and it seems it has deployed ok.
![screen shot 2018-02-02 at 9 47 01 am](https://user-images.githubusercontent.com/21124929/35739017-64fffbfa-07fe-11e8-9888-2773215c86d2.png)

**Comment by innerjoin** [comment]
@rjc570 Thank you for reaching out to us and please excuse my late reply

We have been running the Status History on RTC 6.0.4 for quite a while, the log file excerpt posted by you is looking good and also the setup looks fine to me. It's ok that it says "not available" while adding the presentation (although I would like to know how I can change that label, but that's another story).

One important thing to know is that the status history only shows data if you have saved the work item you are viewing at least once, so I mean that as long as the _History_ tab in RTC does not have any entry, the status history presentation will be a blank box.

To be able to help you to get this up and running, could you check the following:
- One thing that caught my eye is that you seem to be using Mac, so may I ask you what browser are you using? Safari?
- Regarding the debugging technique: Could you open the developer tools of your web browser (typically, this can be done by hitting `F12`) and check out whether there is an `ERROR` in the console view?

**Comment by innerjoin** [comment]
@rjc570 Have you had the chance to look into this again?

**Comment by rjc570** [comment]
Yes.  It is still not working.  I have tried it on a colleagues windows computer using different browsers.  As well I have tried it with Firefox and Chrome on my Mac.  Here are some screenshots.
![screen shot 2018-02-23 at 8 39 17 am](https://user-images.githubusercontent.com/21124929/36596849-1aef3472-1875-11e8-8fbb-99524e955f00.png)
![screen shot 2018-02-23 at 8 40 15 am](https://user-images.githubusercontent.com/21124929/36596881-3b451a8e-1875-11e8-80c6-e46b5ce59022.png)

**Comment by innerjoin** [comment]
@rjc570 To be honest, I have no clue why this is not working

**Comment by mab447** [comment]
I'm not sure this is related, but the plugin did not work for us either. It looks to be a locale issue. The modified time, match expression, was using a '+' instead of a '-' for the last 4 digits. When I changed this everything worked as it should.   The match filter is in Presentation.js in the createStateHistory function. I used RESTClient to run the GET on the workitem history and see what our date format looked like (which did not have a + in it).

**Comment by rjc570** [comment]
Where did you find this file, Presentation.js, to change?  I did a search in my server directory and could not find it.

**Comment by mab447** [comment]
It's a file inside the Plugins JAR file.
you'll have to open the jar file in the Plugins folder, make the edit, and update the file in the jar or repackage the jar.  Once you open the plugin, you'll find the file in the /resources/ui folder.

**Comment by rjc570** [comment]
Is this the line you modified?
`					var exp = /(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}\+\d{2})(\d{2})/;`

**Comment by mab447** [comment]
yes, for my server the format was: 
var exp = /(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}\-\d{2})(\d{2})/;

You should check the format on your server before changing the code,  the request in that function is what returns the modified time for each state change in history. (the base URL is https://_server_:_port_/ccm/)

**Comment by innerjoin** [comment]
@mab447 Thank you so much for your help. This seems to be the root cause and I was able to reproduce thiss on my side for servers with a negative time zone offset. I will attach a bugfix and create a new, patched release of it.

**Comment by innerjoin** [comment]
@rjc570 and @mab447: Please try [Version 2.2.5](https://github.com/jazz-community/rtc-statushistory-presentation/releases/tag/v2.2.5) and let me know if this solves your issue.

**Comment by rjc570** [comment]
I can confirm version 2.2.5 is working.  Thanks for all the efforts.

**Comment by innerjoin** [comment]
Great, good to hear that :-)
