### ISSUE TITLE
Rich hover on the state within the box may show the full change done together with the statechange

### ISSUE THREAD

**Issue by schneigu** [jazz-community/rtc-statushistory-presentation#2]
It would be useful to quickly see all changes done with the statechange.

Maybe something can be done like on the event dashboard widget?

**Comment by innerjoin** [comment]
@schneigu What's your opinion on the attached prototype?

![fullstate_suggestion](https://user-images.githubusercontent.com/2387965/28787661-6ecd43ae-761d-11e7-9746-37ebf74865a6.png)

**Comment by schneigu** [comment]
@innerjoin It's nearly perfect. Only thing I did not liked at the beginning is, the Hover dialog is overlying the owner picture and the number of days in the state. 
I understand the rich hover is bound to the box so this is expected. Maybe the Owner picture and the number of days should move to the right of the box?

**Comment by innerjoin** [comment]
What about showing the following on top of the change summary within the tooltip:

> ![me](https://avatars3.githubusercontent.com/u/2387965?v=4&s=88) Lukas Steiger changed on 31 Jul 2017:
> ((current tooltip content))

I'd personally prefer that solution in favor of aligning the timeline on the right side. What do you think?

**Comment by schneigu** [comment]
Add number of days in the text like " changed on date (3 days ago)".

Or similar.

Then go for it.
