### ISSUE TITLE
Show how many days the workitem is/was in a state.

### ISSUE THREAD

**Issue by schneigu** [jazz-community/rtc-statushistory-presentation#3]
Especially for defect management it is good to know how long the workitem was in a particular state.
This could be visualized in e.g. days.
Show it maybe in the lower right corner.

**Comment by innerjoin** [comment]
I like this idea as it makes it much easier to compare between states. I'm currently working on a timeline like UI in which this idea fits very well

**Comment by innerjoin** [comment]
closed  by above commit
