### ISSUE TITLE
Allow to show State Icon instead of picture of the user

### ISSUE THREAD

**Issue by schneigu** [jazz-community/rtc-statushistory-presentation#6]
In some usecases we like to see a State Icon in the timeline instead of the Name of the user who did the change.
The username name should be displayed textual instead of the state.

The state icon should be selected out of the process attachments. But it should be possible to display a image with a higher resolution than the normal 16x16 pixel of an Icon if one is available. Maybe by using a naming convention. E.g. iconname_highres.gif

**Comment by chakuew0** [comment]
As example we could use for 8D
https://bt-clmserver01.hqs.sbt.siemens.com/ccm/resource/itemName/com.ibm.team.workitem.WorkItem/499763

**Comment by innerjoin** [comment]
@chakuew0 I had to delete your comment as it points to a non-public URL

**Comment by innerjoin** [comment]
Starting with [Release 2.2.0](https://github.com/jazz-community/rtc-statushistory-presentation/releases/tag/v2.2.0), set the following configuration properties to enable this feature:

| Key              | Value         |
| ---------------- | ------------- | 
| timeline         | STATUS |
| largeIcons       | true | 
| largeIconsSuffix | _large.svg      | 

(creates a Status based history, which looks for process attachments with a *_large.svg* suffix)

https://github.com/jazz-community/rtc-statushistory-presentation/blob/master/documentation/statusHistoryPresentation_V2.2.0.png
