### ISSUE TITLE
Status history plugin didn't show the history after deployment

### ISSUE THREAD

**Issue by saina110** [jazz-community/rtc-statushistory-presentation#7]
Dear all,

Recently, I've tried to deploy the ststua history plugin into our formal RTC template in ALM. But after following your guide, we didn't see the history in the tab, shown as below:

![screenshot](https://user-images.githubusercontent.com/11236663/30046801-e8dd360c-923f-11e7-80ec-599f08fa0c5c.png)

It is blank after we change several times for the 'task' status, could you give us some suggestion on this issue? Thank you so much!

**Comment by innerjoin** [comment]
Hi @saina110 
Thank you very much for reporting this to me. I've stumbled across an issue just now using the latest 2.2.0 release. It has the same consequences on my side so I assume it is the same issue. I'm currently testing the bug fix for this issue...

**Comment by innerjoin** [comment]
@saina110  have a look at [Release 2.2.1](https://github.com/jazz-community/rtc-statushistory-presentation/releases/tag/v2.2.1) and please let me know whether this fixes your issue or not

**Comment by innerjoin** [comment]
Closing this issue as I assume the latest release has fixed it. If not, please let me know.

**Comment by saina110** [comment]
Hello Innerjoin,

Thank you for your fixing. Now the 2.2.1 version is working for our ALM, shown as below:

![screenshot](https://user-images.githubusercontent.com/11236663/30092495-e44c43a0-92f1-11e7-9e97-4f9ed3e65653.png)

Thank you:)
